/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.sql.*;
import java.util.logging.Level;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.logging.Logger;
import static javaapplication3.EMPLOYEE.con;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import static javaapplication3.EMPLOYEE.con;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form CLIENTS
     */
    public Sales() {
        initComponents();
        this.setLocationRelativeTo(null);
    fill_table(Sales_s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NAT_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        car_model = new javax.swing.JTextField();
        addclient = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        car_type = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sellprice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sales_s = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        car_color = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        first_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client`s Information");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 0, 18));

        jPanel2.setBackground(new java.awt.Color(32, 31, 29));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALES  :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last-Name");

        last_name.setBackground(new java.awt.Color(32, 31, 29));
        last_name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail : ");

        email.setBackground(new java.awt.Color(32, 31, 29));
        email.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("National ID :");

        NAT_ID.setBackground(new java.awt.Color(32, 31, 29));
        NAT_ID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        NAT_ID.setForeground(new java.awt.Color(255, 255, 255));
        NAT_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        NAT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAT_IDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone-Number : ");

        phone.setBackground(new java.awt.Color(32, 31, 29));
        phone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Car Type:");

        car_model.setBackground(new java.awt.Color(32, 31, 29));
        car_model.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        car_model.setForeground(new java.awt.Color(255, 255, 255));
        car_model.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        car_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_modelActionPerformed(evt);
            }
        });

        addclient.setBackground(new java.awt.Color(32, 31, 29));
        addclient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addclient.setForeground(new java.awt.Color(192, 0, 18));
        addclient.setText("SELL");
        addclient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        addclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Car Model:");

        car_type.setBackground(new java.awt.Color(32, 31, 29));
        car_type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        car_type.setForeground(new java.awt.Color(255, 255, 255));
        car_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        car_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_typeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sell Price");

        sellprice.setBackground(new java.awt.Color(32, 31, 29));
        sellprice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        sellprice.setForeground(new java.awt.Color(255, 255, 255));
        sellprice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        sellprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellpriceActionPerformed(evt);
            }
        });

        Sales_s.setBackground(new java.awt.Color(51, 51, 51));
        Sales_s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sales_s.setForeground(new java.awt.Color(255, 255, 255));
        Sales_s.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Sales_s);

        jLabel9.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Car Color:");

        car_color.setBackground(new java.awt.Color(32, 31, 29));
        car_color.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        car_color.setForeground(new java.awt.Color(255, 255, 255));
        car_color.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        car_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_colorActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(32, 31, 29));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        first_name.setBackground(new java.awt.Color(32, 31, 29));
        first_name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        first_name.setForeground(new java.awt.Color(255, 255, 255));
        first_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First-Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NAT_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(car_model, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(car_color, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sellprice)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addclient, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_model, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_color, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addclient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellprice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void NAT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAT_IDActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void car_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_modelActionPerformed

    private void addclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclientActionPerformed
        if (!(valid_input())) {
            return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");

            

            PreparedStatement pst = con.prepareStatement("Select *from customers where National_Id=?");
            pst.setString(1, NAT_ID.getText());
            
            ResultSet rs = pst.executeQuery();
            if (!rs.next()) {
                pst = con.prepareStatement("insert into customers(National_Id,First_Name,Last_Name,Phone,Email)"
                        + "values(?,?,?,?,?)");
                pst.setString(1, NAT_ID.getText());
                pst.setString(2, first_name.getText());
                pst.setString(3, last_name.getText());
                pst.setString(4, phone.getText());
                pst.setString(5, email.getText());
                pst.executeUpdate();
            }
            pst = con.prepareStatement("update cars set Counter = (Counter-1) where company_id = (select Company_Id from company where Company_Name = ?)and cars.Color=? and cars.Model=?;");
            pst.setString(1, car_type.getText());
            pst.setString(2, car_color.getText());
            pst.setString(3, car_model.getText());
            pst.executeUpdate();
            

            LocalDateTime currentDateTime = LocalDateTime.now();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
            String time = currentDateTime.format(formatter);
      
            pst = con.prepareStatement("insert into sales(Car_Id,Sale_Date,Sale_Price,Client_Nat_Id)values((Select Car_ID from cars where Color=? and Model=? and company_id=(select Company_Id from company where Company_Name=?)),?,?,?);");
            pst.setString(1, car_color.getText());
            pst.setString(2, car_model.getText());
            pst.setString(3, car_type.getText());
            pst.setString(4, time);
            pst.setString(5, sellprice.getText());
            pst.setString(6, NAT_ID.getText());
             pst.executeUpdate();
            fill_table(Sales_s);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Check The Correction of Inputed car");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_addclientActionPerformed

    private void car_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_typeActionPerformed

    private void car_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_colorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HOME BK = new HOME();
        BK.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void sellpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellpriceActionPerformed
    public static void fill_table(javax.swing.JTable t) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");
            Statement st = con.createStatement();
            String query = "select sales.Id,customers.First_Name ,customers.Last_Name,customers.Phone,sales.Sale_Date,sales.Sale_Price,company.Company_Name,cars.Model,cars.Color from sales inner join customers on sales.Client_Nat_Id=customers.National_Id inner join cars on sales.Car_Id=cars.Car_Id inner join company on cars.company_id=company.Company_Id;";
            
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            int cols = rsmd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) t.getModel();
            model.setRowCount(0);
            model.setColumnCount(0);

            String[] columnNames = new String[cols];
            for (int i = 0; i < cols; i++) {
                columnNames[i] = rsmd.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(columnNames);
            while (rs.next()) {
                Object[] rowData = new Object[cols];
                for (int i = 0; i < cols; i++) {
                    rowData[i] = rs.getObject(i + 1);
                }
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error fetching data: " + ex.getMessage());
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public boolean valid_input() {
        boolean ok = true;
        if (((first_name.getText().isEmpty()) || (last_name.getText().isEmpty()) || (email.getText().isEmpty()) || (NAT_ID.getText().isEmpty()) || (phone.getText().isEmpty()) || (car_type.getText().isEmpty()) || (car_model.getText().isEmpty()) || (car_color.getText().isEmpty()) || (sellprice.getText().isEmpty()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Check That All fields are inputed");
            ok = false;
        }
        if (!(Funs.valid_name(last_name.getText())) || !(Funs.valid_name(first_name.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid name that contains Characters and '_' only ");
            last_name.setText("");
            first_name.setText("");
            ok = false;
        }
        if (!(email.getText().contains("@"))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid Email address");
            email.setText("");
            ok = false;
        }
        if (!(Funs.only_nums(NAT_ID.getText())) || (NAT_ID.getText().length() != 14)) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid National Id that only Contains Numbers with Length 14 Number");
            NAT_ID.setText("");
            ok = false;
        }
        if (!(Funs.only_nums(phone.getText())) || (phone.getText().length() != 11)) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid Phone Number that only Contains Numbers With Length 11 Number");
            phone.setText("");
            ok = false;
        }
        if (!(Funs.valid_name(car_type.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-TYPE that contains Characters ");
            car_type.setText("");
            ok = false;
        }
        if (!(Funs.only_nums_alphs_name(car_model.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-MODEL that contains Characters ");
            car_model.setText("");
            ok = false;
        }

        if (!(Funs.only_nums(sellprice.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid Sell Price that only Contains Numbers");
            sellprice.setText("");
            ok = false;
        }
        if (!(Funs.valid_name(car_color.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-COLOR that contains Characters ");
            car_color.setText("");
            ok = false;
        }
        return ok;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NAT_ID;
    private javax.swing.JTable Sales_s;
    private javax.swing.JButton addclient;
    private javax.swing.JTextField car_color;
    private javax.swing.JTextField car_model;
    private javax.swing.JTextField car_type;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField sellprice;
    // End of variables declaration//GEN-END:variables
}
