/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class SIGNUP extends javax.swing.JFrame {
    /**
     * Creates new form SIGNUP
     */
    public SIGNUP(){
        initComponents();
        this.setLocationRelativeTo(null);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        NAT_ID = new javax.swing.JTextField();
        phone_number = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        confirm_pass = new javax.swing.JPasswordField();
        shk_terms = new javax.swing.JCheckBox();
        sign_up = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        signin_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN_UP");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 0, 18));

        jPanel2.setBackground(new java.awt.Color(32, 31, 29));

        jLabel2.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First-Name :");

        jLabel3.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail : ");

        jLabel4.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("National ID :");

        jLabel5.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone-Number : ");

        jLabel6.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password :  ");

        jLabel7.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm  Password : ");

        salary.setBackground(new java.awt.Color(32, 31, 29));
        salary.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        salary.setForeground(new java.awt.Color(255, 255, 255));
        salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });

        email.setBackground(new java.awt.Color(32, 31, 29));
        email.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        NAT_ID.setBackground(new java.awt.Color(32, 31, 29));
        NAT_ID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        NAT_ID.setForeground(new java.awt.Color(255, 255, 255));
        NAT_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        NAT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAT_IDActionPerformed(evt);
            }
        });

        phone_number.setBackground(new java.awt.Color(32, 31, 29));
        phone_number.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        phone_number.setForeground(new java.awt.Color(255, 255, 255));
        phone_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numberActionPerformed(evt);
            }
        });

        pass.setBackground(new java.awt.Color(32, 31, 29));
        pass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));

        confirm_pass.setBackground(new java.awt.Color(32, 31, 29));
        confirm_pass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        confirm_pass.setForeground(new java.awt.Color(255, 255, 255));
        confirm_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));

        shk_terms.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        shk_terms.setForeground(new java.awt.Color(255, 255, 255));
        shk_terms.setText("I have read all terms and accept it !!");
        shk_terms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shk_termsActionPerformed(evt);
            }
        });

        sign_up.setBackground(new java.awt.Color(32, 31, 29));
        sign_up.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign_up.setForeground(new java.awt.Color(192, 0, 18));
        sign_up.setText("SIGN UP");
        sign_up.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Already have an acount??");

        signin_btn.setBackground(new java.awt.Color(32, 31, 29));
        signin_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signin_btn.setForeground(new java.awt.Color(192, 0, 18));
        signin_btn.setText("SIGN IN");
        signin_btn.setBorderPainted(false);
        signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_btnActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NOW !!");

        position.setBackground(new java.awt.Color(32, 31, 29));
        position.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        position.setForeground(new java.awt.Color(255, 255, 255));
        position.setMaximumRowCount(2);
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Sales" }));
        position.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Position: ");

        first_name.setBackground(new java.awt.Color(32, 31, 29));
        first_name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        first_name.setForeground(new java.awt.Color(255, 255, 255));
        first_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Second-Name :");

        jLabel13.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Salary");

        last_name.setBackground(new java.awt.Color(32, 31, 29));
        last_name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signin_btn)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shk_terms)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NAT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(shk_terms)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(signin_btn)
                    .addComponent(jLabel9))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resizedblack .png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void NAT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAT_IDActionPerformed

    private void phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numberActionPerformed

    private void shk_termsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shk_termsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shk_termsActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
Boolean ok=true;
        String password = String.valueOf(pass.getPassword()); // Extract password as String
        String confirmPassword = String.valueOf(confirm_pass.getPassword());
        if (((last_name.getText().isEmpty())||(first_name.getText().isEmpty()) || (email.getText().isEmpty()) || (NAT_ID.getText().isEmpty()) || (phone_number.getText().isEmpty())) || ((password.length() == 0) || confirmPassword.length() == 0)) {
            JOptionPane.showMessageDialog(this, "Error,Please Check That All fields are inputed");
            ok=false;
        }
           if (!(Funs.valid_name(first_name.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid name that contains Characters and '_' only ");
            first_name.setText("");
            ok=false;
    }
        if (!(Funs.valid_name(last_name.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid name that contains Characters and '_' only ");
            last_name.setText("");
            ok=false;
    }                                       
        if (!(email.getText().contains("@"))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid Email address");
            email.setText("");
            ok=false;
        }
        if (!(Funs.only_nums(NAT_ID.getText())) || (NAT_ID.getText().length() != 14)) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid National Id that only Contains Numbers with Length 14 Number");
            NAT_ID.setText("");
            ok=false;
        }
        if (!(Funs.only_nums(phone_number.getText())) || (phone_number.getText().length() != 11)) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid Phone Number that only Contains Numbers");
            phone_number.setText("");
            ok=false;
        }
        if(! Funs.checkPasswordMatch(password,confirmPassword))
        {
            JOptionPane.showMessageDialog(this,"Error,Please Check That The Password Equals The Confirmed Password ");
            pass.setText("");
            confirm_pass.setText("");
            ok=false;
        }
        if(!Funs.only_nums(salary.getText()))
        {
            JOptionPane.showMessageDialog(this,"Error,Please Check That The Salary Have Only Numbers");
            salary.setText("");
            ok=false;
        }
          if (!shk_terms.isSelected()) {
            JOptionPane.showMessageDialog(this, "Error,Please Read and accept terms to log in");
            ok=false;
        }
          if(ok==false)return;
        try {
    // Load the MySQL JDBC driver
    Class.forName("com.mysql.cj.jdbc.Driver");

    // Establish a connection to the database
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");

    // Create a PreparedStatement to insert data
    String query = "INSERT INTO employees (First_Name, Last_Name, Position, Phone, Email, National_Id,salary,Password) VALUES (?, ?, ?, ?, ?, ?, ?,?)";
    PreparedStatement pst = con.prepareStatement(query);
    // Set the values
    pst.setString(1, first_name.getText());
    pst.setString(2, last_name.getText());
    pst.setString(3, (String) position.getSelectedItem());
    pst.setString(4, phone_number.getText());
    pst.setString(5, email.getText());
    pst.setString(6, NAT_ID.getText());
    pst.setString(7, salary.getText());
    pst.setString(8, String.valueOf(pass.getPassword()));

    // Execute the update
    int rowsAffected = pst.executeUpdate();

    // Check if the operation was successful
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Employee added successfully , Now you Can Sign in with Your Account");
        LOGIN log=new LOGIN();
        log.show();
        dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add employee.");
    }

} catch (ClassNotFoundException ex) {
    JOptionPane.showMessageDialog(this, "Connection Error with Database");
} catch (SQLException ex) {
    ex.printStackTrace(); // Optional: Log the error for debugging
    JOptionPane.showMessageDialog(this, "Error executing the database operation");
}
    }//GEN-LAST:event_sign_upActionPerformed

    private void signin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_btnActionPerformed
        // TODO add your handling code here:
        LOGIN log=new LOGIN();
        log.show();
        dispose();
    }//GEN-LAST:event_signin_btnActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionActionPerformed
 
    /**
     * @param args the command line arguments
     */
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NAT_ID;
    private javax.swing.JPasswordField confirm_pass;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField last_name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone_number;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField salary;
    private javax.swing.JCheckBox shk_terms;
    private javax.swing.JButton sign_up;
    private javax.swing.JButton signin_btn;
    // End of variables declaration//GEN-END:variables
}
