/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import static javaapplication3.EMPLOYEE.con;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Omar
 */
public class STOCK extends javax.swing.JFrame {

    int selected_car_id;

    /**
     * Creates new form STOCK
     */
    public STOCK() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            // jdbc:mysql://localhost:3306/
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Base Connection Failed");
        }
        fill_table(stockT);
        ////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        addcar = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        stockT = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Numbers = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARS`S INFORMATION");
        setPreferredSize(new java.awt.Dimension(1163, 695));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 0, 18));

        jPanel2.setBackground(new java.awt.Color(32, 31, 29));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cars`s Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company:");

        Type.setBackground(new java.awt.Color(32, 31, 29));
        Type.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Car Model:");

        Model.setBackground(new java.awt.Color(32, 31, 29));
        Model.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Model.setForeground(new java.awt.Color(255, 255, 255));
        Model.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Car Price:");

        price.setBackground(new java.awt.Color(32, 31, 29));
        price.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Car Color:");

        color.setBackground(new java.awt.Color(32, 31, 29));
        color.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        color.setForeground(new java.awt.Color(255, 255, 255));
        color.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        addcar.setBackground(new java.awt.Color(32, 31, 29));
        addcar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addcar.setForeground(new java.awt.Color(192, 0, 18));
        addcar.setText("Add Car");
        addcar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        addcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcarActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(32, 31, 29));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(192, 0, 18));
        Update.setText("Update");
        Update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(32, 31, 29));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(192, 0, 18));
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        stockT.setBackground(new java.awt.Color(51, 51, 51));
        stockT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockT.setForeground(new java.awt.Color(255, 255, 255));
        stockT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Car_Id", "Color", "Model", "Price", "Counter", "Company_Name"
            }
        ));
        stockT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(stockT);

        jLabel11.setFont(new java.awt.Font("VIP Rawy Regular", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Car Numbers:");

        Numbers.setBackground(new java.awt.Color(32, 31, 29));
        Numbers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Numbers.setForeground(new java.awt.Color(255, 255, 255));
        Numbers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 0, 18), 1, true));
        Numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbersActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(32, 31, 29));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setForeground(new java.awt.Color(192, 0, 18));
        Clear.setText("Clear-All");
        Clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 0, true));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(Type)
                    .addComponent(Numbers))
                .addGap(134, 134, 134)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addcar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void addcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcarActionPerformed
        if (!(valid_input())) {
            return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");

            PreparedStatement pst = con.prepareStatement("SELECT * FROM company WHERE Company_Name=?");
            pst.setString(1, Type.getText());
            ResultSet rs = pst.executeQuery();

            int companyId = 0;
            if (!rs.next()) {
                pst = con.prepareStatement("INSERT INTO company (Company_Name) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
                pst.setString(1, Type.getText());
                pst.executeUpdate();
                ResultSet generatedKeys = pst.getGeneratedKeys();
                if (generatedKeys.next()) {
                    companyId = generatedKeys.getInt(1);
                }
            } else {
                // Get existing Company_Id
                companyId = rs.getInt("Company_Id");
            }

            pst = con.prepareStatement("SELECT * FROM cars WHERE Price=? AND Color=? AND company_id=? AND Model=?");
            pst.setInt(1, Integer.parseInt(price.getText()));
            pst.setString(2, color.getText());
            pst.setInt(3, companyId);
            pst.setString(4, Model.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                
                pst = con.prepareStatement("UPDATE cars SET Counter = Counter + ? WHERE Price=? AND Color=?AND company_id=? AND Model=?");
                pst.setInt(1, Integer.parseInt(Numbers.getText()));
                pst.setInt(2, Integer.parseInt(price.getText()));
                pst.setString(3, color.getText());
                pst.setInt(4, companyId);
                pst.setString(5, Model.getText());
                pst.executeUpdate();
            } else {
               
                pst = con.prepareStatement("INSERT INTO cars (Price, Color, Model, Counter, company_id) VALUES (?, ?, ?,?, ?)");
                pst.setInt(1, Integer.parseInt(price.getText()));
                pst.setString(2, color.getText());
                pst.setString(3, Model.getText());
                pst.setInt(4, Integer.parseInt(Numbers.getText()));
                pst.setInt(5, companyId);
                pst.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Operation completed successfully.");
            fill_table(stockT);
            clear_fields();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addcarActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if (!(valid_input())) {
            return;
        }
        if (stockT.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select A Row First To Can Update It");
            return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM company WHERE Company_Name=?");
            pst.setString(1, Type.getText());
            ResultSet rs = pst.executeQuery();
            int companyId = 0;
            if (!rs.next()) {
                pst = con.prepareStatement("INSERT INTO company (Company_Name) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
                pst.setString(1, Type.getText());
                pst.executeUpdate();
                ResultSet generatedKeys = pst.getGeneratedKeys();
                if (generatedKeys.next()) {
                    companyId = generatedKeys.getInt(1);
                }
            } else {
                companyId = rs.getInt("Company_Id");
            }
            pst = con.prepareStatement("UPDATE cars SET Color = ?, Model = ?, Price = ?, Counter = ? ,company_id=? WHERE Car_Id = ?");
            pst.setString(1, color.getText());
            pst.setString(2, Model.getText());
            pst.setString(3, price.getText());
            pst.setString(4, Numbers.getText());
            pst.setInt(5, companyId);
            pst.setInt(6, selected_car_id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Update completed successfully.");
            fill_table(stockT);
            clear_fields();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HOME BK = new HOME();
        BK.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void NumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumbersActionPerformed

    private void stockTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTMouseClicked
        Type.setText(stockT.getValueAt(stockT.getSelectedRow(), 5).toString());
        Numbers.setText(stockT.getValueAt(stockT.getSelectedRow(), 4).toString());
        price.setText(stockT.getValueAt(stockT.getSelectedRow(), 3).toString());
        Model.setText(stockT.getValueAt(stockT.getSelectedRow(), 2).toString());
        color.setText(stockT.getValueAt(stockT.getSelectedRow(), 1).toString());
        selected_car_id = Integer.parseInt(stockT.getValueAt(stockT.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_stockTMouseClicked

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        clear_fields();
    }//GEN-LAST:event_ClearActionPerformed
    private void clear_fields() {
        Type.setText("");
        price.setText("");
        color.setText("");
        Model.setText("");
        Numbers.setText("");
    }

    public boolean valid_input() {
        boolean ok = true;
        if (((Type.getText().isEmpty()) || (Model.getText().isEmpty()) || (color.getText().isEmpty()) || (price.getText().isEmpty()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Check That All fields are inputed");
            ok = false;
        }
        if (!(Funs.only_alphs(Type.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-TYPE that contains Characters ");
            Type.setText("");
            ok = false;
        }
        if (!(Funs.only_nums_alphs_name(Model.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-MODEL that contains Characters Or Numbers ");
            Model.setText("");
            ok = false;
        }

        if (!(Funs.only_nums(price.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a Valid Price that only Contains Positive Numbers");
            price.setText("");
            ok = false;
        }
        if (!(Funs.only_alphs(color.getText()))) {
            JOptionPane.showMessageDialog(this, "Error,Please Enter a valid CAR-COLOR that contains Characters ");
            color.setText("");
            ok = false;
        }
        return ok;
    }

    public static void fill_table(javax.swing.JTable t) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_semsar", "root", "root");
            Statement st = con.createStatement();
            String query = "SELECT cars.Car_Id, cars.Color, cars.Model, cars.Price, cars.Counter, company.Company_Name FROM cars INNER JOIN company ON cars.company_id = company.Company_Id";
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            int cols = rsmd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) t.getModel();
            model.setRowCount(0);
            model.setColumnCount(0);

            String[] columnNames = new String[cols];
            for (int i = 0; i < cols; i++) {
                columnNames[i] = rsmd.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(columnNames);
            while (rs.next()) {
                Object[] rowData = new Object[cols];
                for (int i = 0; i < cols; i++) {
                    rowData[i] = rs.getObject(i + 1);
                }
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error fetching data: " + ex.getMessage());
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new STOCK().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(STOCK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Model;
    private javax.swing.JTextField Numbers;
    private javax.swing.JTextField Type;
    private javax.swing.JButton Update;
    private javax.swing.JButton addcar;
    private javax.swing.JTextField color;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField price;
    private javax.swing.JTable stockT;
    // End of variables declaration//GEN-END:variables
}
